export const ICON_PATH = {
  safe: {
    connection: {
      "smart-light": "icon green-smartLight.svg",
      "media": "icon green-mediaPlayer.svg",
      "env-sensor": "icon green-environment.svg",
      "solar": "icon green-23.svg",
      "holder": "icon green-holder.svg",
      "NB-IoT": "icon green-NB-IoT.svg",
      "gateway": "icon green-gateway.svg"
    },
    "smart-light": {
      volt: "icon green-15.svg",
      current: "icon green-17.svg",
      brightness: "icon green-16.svg",
      "power-consumption": "icon green-18.svg",
    },
    "env-sensor": {
      temperature: "icon green-temperature.svg",
      humidity: "icon green-humidity.svg",
      "pm2.5": "icon green-09.svg",
      pm10: "icon green-10.svg",
      o3: "icon green-11.svg",
      co: "icon green-12.svg",
      no2: "icon green-13.svg",
      so2: "icon green-14.svg",
    },
    "save-energy": {
      "volt-charge": "icon green-19.svg",
      "current-charge": "icon green-21.svg",
      "volt-discharge": "icon green-20.svg",
      "current-discharge": "icon green-22.svg",
      "power-charge": "icon green-inputPower.svg",
      "power-discharge": "icon green-outputPower.svg",
      battery: "icon green-23.svg",
      temperature: "icon green-temperature.svg",
    },
  },
  warning: {
    connection: {
      "smart-light": "icon red-smartLight.svg",
      "media": "icon red-mediaPlayer.svg",
      "env-sensor": "icon red-environment.svg",
      "solar": "icon red-23.svg",
      "holder": "icon red-holder.svg",
      "NB-IoT": "icon red-NB-IoT.svg",
      "gateway": "icon red-gateway.svg"
    },
    "smart-light": {
      volt: "icon red-15.svg",
      current: "icon red-17.svg",
      brightness: "icon red-16.svg",
      "power-consumption": "icon red-18.svg",
    },
    "env-sensor": {
      temperature: "icon red-temperature.svg",
      humidity: "icon red-humidity.svg",
      "pm2.5": "icon red-09.svg",
      pm10: "icon red-10.svg",
      o3: "icon red-11.svg",
      co: "icon red-12.svg",
      no2: "icon red-13.svg",
      so2: "icon red-14.svg",
    },
    "save-energy": {
      "volt-charge": "icon red-19.svg",
      "current-charge": "icon red-21.svg",
      "volt-discharge": "icon red-20.svg",
      "current-discharge": "icon red-22.svg",
      "power-charge": "icon red-inputPower.svg",
      "power-discharge": "icon red-outputPower.svg",
      battery: "icon red-23.svg",
      temperature: "icon red-temperature.svg",
    },
  },
  disabled: {
    connection: {
      "smart-light": "icon gray-smartLight.svg",
      "media": "icon gray-mediaPlayer.svg",
      "env-sensor": "icon gray-environment.svg",
      "solar": "icon gray-23.svg",
      "holder": "icon gray-holder.svg",
      "NB-IoT": "icon gray-NB-IoT.svg",
      "gateway": "icon gray-gateway.svg"
    },
    "smart-light": {
      volt: "icon gray-15.svg",
      current: "icon gray-17.svg",
      brightness: "icon gray-16.svg",
      "power-consumption": "icon gray-18.svg",
    },
    "env-sensor": {
      temperature: "icon gray-temperature.svg",
      humidity: "icon gray-humidity.svg",
      "pm2.5": "icon gray-09.svg",
      pm10: "icon gray-10.svg",
      o3: "icon gray-11.svg",
      co: "icon gray-12.svg",
      no2: "icon gray-13.svg",
      so2: "icon gray-14.svg",
    },
    "save-energy": {
      "volt-charge": "icon gray-19.svg",
      "current-charge": "icon gray-21.svg",
      "volt-discharge": "icon gray-20.svg",
      "current-discharge": "icon gray-22.svg",
      "power-charge": "icon gray-inputPower.svg",
      "power-discharge": "icon gray-outputPower.svg",
      battery: "icon gray-23.svg",
      temperature: "icon gray-temperature.svg",
    },
  },
};
